from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_login
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: UNI
    Package: TestProject.Generated.Tests.UNI
    Test: Visualizar y Descargar Facturas
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 11/24/2021, 04:51:39
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="x6PXj5-eahE46Inrl9QG8pLmS8Q_OtYb1rEa1osKZAQ",
                              project_name="UNI",
                              job_name="Visualizar y Descargar Facturas")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://facturaciononempresa.herokuapp.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Run Login
    test_login.test_main(driver)

    # 3. Click 'Facturas'
    facturas = driver.find_element(By.XPATH,
                                   "//a[. = 'Facturas']")
    facturas.click()

    # 4. Click 'A2'
    a2 = driver.find_element(By.XPATH,
                             "//td/a")
    a2.click()
