from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from src.testproject.sdk.drivers.actions import Actions
from subtests import test_login
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: UNI
    Package: TestProject.Generated.Tests.UNI
    Test: Agregar Producto con Stock
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 11/24/2021, 01:20:40
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="x6PXj5-eahE46Inrl9QG8pLmS8Q_OtYb1rEa1osKZAQ",
                              project_name="UNI",
                              job_name="Agregar Producto con Stock")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://facturaciononempresa.herokuapp.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Run Login
    test_login.test_main(driver)

    # 3. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 4. Click 'Computadores Portatiles'
    computadores_portatiles = driver.find_element(By.XPATH,
                                                  "//a[. = 'Computadores Portatiles']")
    computadores_portatiles.click()

    # 5. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 6. Click 'MacBook Pro 2019'
    macbook_pro_2019 = driver.find_element(By.XPATH,
                                           "//a[. = 'MacBook Pro 2019']")
    macbook_pro_2019.click()

    # 7. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 8. Click 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//div/input[2]")
    input2.click()

    # 9. Pause for '2000'ms
    driver.pause(milliseconds=2000)

    # 10. Click 'Carrito'
    carrito = driver.find_element(By.XPATH,
                                  "//a[. = '  Carrito\n\t\t\t\t\t']")
    carrito.click()
