from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_login
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: UNI
    Package: TestProject.Generated.Tests.UNI
    Test: Registro de Usuario
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 11/24/2021, 00:49:54
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="x6PXj5-eahE46Inrl9QG8pLmS8Q_OtYb1rEa1osKZAQ",
                              project_name="UNI",
                              job_name="Registro de Usuario")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://facturaciononempresa.herokuapp.com/"
    nombreUsuario = ""
    contrasena = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Iniciar Sesión'
    iniciar_sesi_n = driver.find_element(By.XPATH,
                                         "//a[. = 'Iniciar Sesión']")
    iniciar_sesi_n.click()

    # 3. Click 'Regístrate aquí ¡es gratis!'
    reg_strate_aqu_es_gratis_ = driver.find_element(By.CSS_SELECTOR,
                                                    "#registrar_link")
    reg_strate_aqu_es_gratis_.click()

    # 4. Click 'dni'
    dni = driver.find_element(By.CSS_SELECTOR,
                              "#dni")
    dni.click()

    # 5. Type '1004917211' in 'dni'
    dni = driver.find_element(By.CSS_SELECTOR,
                              "#dni")
    dni.send_keys("1004917211")

    # 6. Click 'nombre'
    nombre = driver.find_element(By.CSS_SELECTOR,
                                 "#nombre")
    nombre.click()

    # 7. Type 'Maria Fernanda' in 'nombre'
    nombre = driver.find_element(By.CSS_SELECTOR,
                                 "#nombre")
    nombre.send_keys("Maria Fernanda")

    # 8. Click 'apellido'
    apellido = driver.find_element(By.CSS_SELECTOR,
                                   "#apellido")
    apellido.click()

    # 9. Type 'Bernal Laverde' in 'apellido'
    apellido = driver.find_element(By.CSS_SELECTOR,
                                   "#apellido")
    apellido.send_keys("Bernal Laverde")

    # 10. Click 'nombreUsuario1'
    nombreusuario1 = driver.find_element(By.CSS_SELECTOR,
                                         "#nombreUsuario")
    nombreusuario1.click()

    # 11. Type 'mafe.bernal' in 'nombreUsuario1'
    nombreusuario1 = driver.find_element(By.CSS_SELECTOR,
                                         "#nombreUsuario")
    nombreusuario1.send_keys("mafe.bernal")

    # 12. Click 'contrasena'
    contrasena = driver.find_element(By.CSS_SELECTOR,
                                     "[name='contrasena']")
    contrasena.click()

    # 13. Type '123456789' in 'contrasena'
    contrasena = driver.find_element(By.CSS_SELECTOR,
                                     "[name='contrasena']")
    contrasena.send_keys("123456789")

    # 14. Click 'telefono'
    telefono = driver.find_element(By.CSS_SELECTOR,
                                   "#telefono")
    telefono.click()

    # 15. Type '3057978883' in 'telefono'
    telefono = driver.find_element(By.CSS_SELECTOR,
                                   "#telefono")
    telefono.send_keys("3057978883")

    # 16. Click 'direccion'
    direccion = driver.find_element(By.CSS_SELECTOR,
                                    "#direccion")
    direccion.click()

    # 17. Type 'Toledo Campestre Casa 27-01' in 'direccion'
    direccion = driver.find_element(By.CSS_SELECTOR,
                                    "#direccion")
    direccion.send_keys("Toledo Campestre Casa 27-01")

    # 18. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//form/div/input")
    input1.click()

    # 19. Run Login
    test_login.test_main(driver)
