from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_login
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: UNI
    Package: TestProject.Generated.Tests.UNI
    Test: Cambiar Bodega
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 11/24/2021, 04:12:32
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="x6PXj5-eahE46Inrl9QG8pLmS8Q_OtYb1rEa1osKZAQ",
                              project_name="UNI",
                              job_name="Cambiar Bodega")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://facturaciononempresa.herokuapp.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Run Login
    test_login.test_main(driver)

    # 3. Click 'INPUT3'
    input3 = driver.find_element(By.XPATH,
                                 "//form[2]/input")
    input3.click()

    # 4. Click 'Producto'
    producto = driver.find_element(By.XPATH,
                                   "//a[. = ' Producto ']")
    producto.click()

    # 5. Click 'Listar Productos'
    listar_productos = driver.find_element(By.XPATH,
                                           "//a[. = 'Listar\n\t\t\t\t\t\t\tProductos']")
    listar_productos.click()

    # 6. Click 'A'
    a = driver.find_element(By.XPATH,
                            "//tr[1]/td[10]/a")
    a.click()

    # 7. Click 'bodega.idBodega'
    bodega_idbodega = driver.find_element(By.CSS_SELECTOR,
                                          "[name='bodega.idBodega']")
    bodega_idbodega.click()

    # 8. Select the '2' option in 'bodega.idBodega'
    bodega_idbodega = driver.find_element(By.CSS_SELECTOR,
                                          "[name='bodega.idBodega']")
    Select(bodega_idbodega).select_by_value("2")

    # 9. Click 'Actualizar Producto'
    actualizar_producto = driver.find_element(By.XPATH,
                                              "//button[. = 'Actualizar\n\t\t\t\tProducto']")
    actualizar_producto.click()
