from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from subtests import test_login
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: UNI
    Package: TestProject.Generated.Tests.UNI
    Test: Registrar Producto
    Generated by: Nicolas Duran (nicolas.duran@atlanticsoft.us)
    Generated on 11/24/2021, 03:34:00
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="x6PXj5-eahE46Inrl9QG8pLmS8Q_OtYb1rEa1osKZAQ",
                              project_name="UNI",
                              job_name="Registrar Producto")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://facturaciononempresa.herokuapp.com/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Run Login
    test_login.test_main(driver)

    # 3. Click 'INPUT3'
    input3 = driver.find_element(By.XPATH,
                                 "//form[2]/input")
    input3.click()

    # 4. Click 'Producto'
    producto = driver.find_element(By.XPATH,
                                   "//a[. = ' Producto ']")
    producto.click()

    # 5. Click 'Registro de Productos'
    registro_de_productos = driver.find_element(By.XPATH,
                                                "//a[. = 'Registro\n\t\t\t\t\t\t\tde Productos']")
    registro_de_productos.click()

    # 6. Click 'nombreProducto'
    nombreproducto = driver.find_element(By.CSS_SELECTOR,
                                         "#nombreProducto")
    nombreproducto.click()

    # 7. Type 'Mouse Gamer' in 'nombreProducto'
    nombreproducto = driver.find_element(By.CSS_SELECTOR,
                                         "#nombreProducto")
    nombreproducto.send_keys("Mouse Gamer")

    # 8. Click 'marca'
    marca = driver.find_element(By.CSS_SELECTOR,
                                "#marca")
    marca.click()

    # 9. Type 'Logitech' in 'marca'
    marca = driver.find_element(By.CSS_SELECTOR,
                                "#marca")
    marca.send_keys("Logitech")

    # 10. Clear 'minimoInventario' contents
    minimoinventario = driver.find_element(By.CSS_SELECTOR,
                                           "#minimoInventario")
    minimoinventario.clear()

    # 11. Click 'minimoInventario'
    minimoinventario = driver.find_element(By.CSS_SELECTOR,
                                           "#minimoInventario")
    minimoinventario.click()

    # 12. Type '9' in 'minimoInventario'
    minimoinventario = driver.find_element(By.CSS_SELECTOR,
                                           "#minimoInventario")
    minimoinventario.send_keys("9")

    # 13. Clear 'cantidadActual' contents
    cantidadactual = driver.find_element(By.CSS_SELECTOR,
                                         "#cantidadActual")
    cantidadactual.clear()

    # 14. Click 'cantidadActual'
    cantidadactual = driver.find_element(By.CSS_SELECTOR,
                                         "#cantidadActual")
    cantidadactual.click()

    # 15. Type '50' in 'cantidadActual'
    cantidadactual = driver.find_element(By.CSS_SELECTOR,
                                         "#cantidadActual")
    cantidadactual.send_keys("50")

    # 16. Clear 'valorUnitario' contents
    valorunitario = driver.find_element(By.CSS_SELECTOR,
                                        "#valorUnitario")
    valorunitario.clear()

    # 17. Click 'valorUnitario'
    valorunitario = driver.find_element(By.CSS_SELECTOR,
                                        "#valorUnitario")
    valorunitario.click()

    # 18. Type '170000' in 'valorUnitario'
    valorunitario = driver.find_element(By.CSS_SELECTOR,
                                        "#valorUnitario")
    valorunitario.send_keys("170000")

    # 19. Click 'categoriaproducto.id_categoriaProduct...'
    categoriaproducto_id_categoriaproduct_ = driver.find_element(By.CSS_SELECTOR,
                                                                 "[name='categoriaproducto.id_categoriaProducto']")
    categoriaproducto_id_categoriaproduct_.click()

    # 20. Click 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[2]/div/input")
    input4.click()
